### ISSUE TITLE
Cannot configure Twitter plugin

### ISSUE THREAD

**Issue by bararchy** [jkakavas/creepy#22]
The problem:
After finishing to configure the Twitter plugin, I put the PIN number on the bar, click finish.
I then continue to press "test plugin configuration" and get this:

![screenshot from 2015-11-23 16-03-04](https://cloud.githubusercontent.com/assets/1631073/11338246/bbf94716-91fb-11e5-8015-674c99e5c083.png)

OS: Arch Linux
Kernel: 4.2.5-1-ARCH
Python: Python 2.7.10
Creepy: Up To Date 1.4.1

Issue log:

```
2015-11-23 15:59:36,609 - yapsy_loaded_plugin_Twitter_Plugin_0 - ERROR - Error authenticating with Twitter API.
2015-11-23 15:59:36,609 - yapsy_loaded_plugin_Twitter_Plugin_0 - ERROR - Unable to get username, invalid oauth token!
2015-11-23 15:59:38,981 - yapsy_loaded_plugin_Twitter_Plugin_0 - ERROR - Error authenticating with Twitter API.
2015-11-23 15:59:38,982 - yapsy_loaded_plugin_Twitter_Plugin_0 - ERROR - Unable to get username, invalid oauth token!
```

**Comment by jkakavas** [comment]
Hi, 

Please check that all the 

'hidden_application_key'
'hidden_application_secret'
'hidden_access_token'
'hidden_access_token_secret'

have values in your twitter.conf file and that the the account who runs python has access to read that file. 
Any other lines in your log file related to this ?

**Comment by bararchy** [comment]
Ok, so apparently I had an older version installed in /usr/share/creepy/
So I had crossing files, removing the /usr/share/creepy/ dir now everything works as intended :)

**Comment by jkakavas** [comment]
Yeap that's not entirely your problem I would say. 

It was part of a code change that would allow the packaging for debian ( creepy looks for the plugins at /usr/share first and falls back to using the pwd/plugins ) at https://github.com/petterreinholdtsen/creepy/commit/7e53b751c695f5817a9314652e5bd32c02b64492 that was implemented in 
https://github.com/jkakavas/creepy/commit/9cb3655e180d5c6946b30d1aba6cb1d7cd6ae0aa

The debian packaging didn't move forward unfortunately, but this has the side effect that if you have an older version installed from your package manager, creepy will default to using the plugins in /usr/share/creepy . That's why for example in Kali 2 I suggest people to remove the debian package first. 

Thanks for bringing it up again, I ll see what I can do to make this more clear
