### ISSUE TITLE
Qt4 > Qt5

### ISSUE THREAD

**Issue by RossGammon** [jkakavas/creepy#9]
Debian are looking to move to Qt5 from Qt4 over the next release cycle. Will Creepy work with python-qt5?

**Comment by jkakavas** [comment]
Hi, from what I've seen in http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html, there are a number of things that affect my code base, like splitting QtGui and QtWebkit in different modules and some other minor things. 

So, a small rewrite might be needed, but I don;t see this as a big effort.

**Comment by petterreinholdtsen** [comment]
Hi.

Do you plan to do this rewrite for a future version of creepy, or leave it as it is and stay with Qt4
until someone else have time to rewrite the code for Qt5?

**Comment by petterreinholdtsen** [comment]
Qt4's WebKit is being dropped from Debian, and because of this the Creepy package in Debian no longer work.  See https://bugs.debian.org/784619 for the release critical issue in Debian.  Is there some alternative to get Creepy working again in Debian?  The status for Creepy in Debian can be seen on https://tracker.debian.org/pkg/creepy .  It is currently removed from 'testing', which is the staging area for the next stable Debian release.

**Comment by RossGammon** [comment]
Hi,
As Qt4's Webkit has been removed from Debian, the latest stable release (Stretch) can no longer run creepy using the standard Debian packages.
A while back, I started work on porting Creepy to Qt5. I have just pushed that unfinished work to my fork:
https://github.com/RossGammon/creepy/tree/qt4-qt5
I don't have the time (or the confidence) to finish the work just now, but I hope you are able to finish it from there so that we can get Creepy back into Debian.
Let me know if you would prefer a PR, so you can more easily merge and finish the work.
Cheers,
Ross
